
export { HomePage } from "./home/home";
export { CarritoPage } from "./carrito/carrito";
export { CategoriasPage} from "./categorias/categorias";
export { LoginPage } from "./login/login";
export { OrdenesPage } from "./ordenes/ordenes";
export { OrdenesDetallePage } from "./ordenes-detalle/ordenes-detalle";
export { PorCategoriasPage } from "./por-categorias/por-categorias";
export { ProductoPage } from "./producto/producto";
export { TabsPage } from "./tabs/tabs";
export { BusquedaPage } from "./busqueda/busqueda";
export { RegistrarsePage } from "./registrarse/registrarse";
export { CompraPage } from "./compra/compra";
export { PaypalPage } from "./paypal/paypal";
export { TarjetaPage } from "./tarjeta/tarjeta";
export { EstacionamientoPage } from "./estacionamiento/estacionamiento";
export { EstacionamientoDetallePage } from "./estacionamiento-detalle/estacionamiento-detalle";
export { EspaciosPage } from "./espacios/espacios";
export { EspaciosDetallePage } from "./espacios-detalle/espacios-detalle";
export { HistorialPage } from "./historial/historial";
export { ReportesPage } from "./reportes/reportes";
export { MantenimientoPage } from "./mantenimiento/mantenimiento";
